---
# defaults file for lumen_deploy

build_filename: build
build_format: zip
build_clear: false

command_composer_install: "composer install"
command_phpunit: "phpunit"
phpunit_enabled: true

app_name: lumen.app
app_directory: "/var/www/{{app_name}}"
app_src: "./src/"

app_db: false
app_cron: false

app_sandbox_enabled: false
app_sandbox_port: 8077
app_sandbox_host: "http://{{inventory_hostname}}:{{app_sandbox_port}}"

app_user: deploy
app_group: deploy

app_directories:
  - "{{app_src}}app"
  - "{{app_src}}bootstrap"
  - "{{app_src}}config"
  - "{{app_src}}database"
  - "{{app_src}}public"
  - "{{app_src}}resources"
  - "{{app_src}}routes"
  - "{{app_src}}vendor"
  - "{{app_src}}artisan"

deploy_extensions:
  - zip
  - unzip
  - curl
  - php-cli

laravel_php_extensions:
  - php-mbstring
  - php-curl
  - php-xml
  - php-zip

app_php_extensions:
  - php-mysql

app_nginx_extensions: []

nginx_log_format: |
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'
