version: "3.6"

services:
  app:
    image: ${IMAGE_APP}
    ports:
      - ${APP_PORT}:80
    volumes:
      - .env:/var/www/html/.env
    environment:
      SKIP_COMPOSER: 1
      SKIP_CHOWN: 1
    links:
      - database

  database:
    image: ${IMAGE_DATABASE}
    volumes:
      - eva-position-db:/var/lib/postgresql/data
#      - ./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    image: ${IMAGE_REDIS}

volumes:
  eva-position-db:
