replicaCount: 1

app:
  postgres:
    host: postgres
    port: 5432
    db: position
    connection: pgsql

image:
  repository: sr2020/eva-position
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi
