apiVersion: v1
kind: Service
metadata:
  name: position
  labels:
    app: position
    tier: position
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: position
    tier: position
